### ISSUE TITLE
Support async for useFactory

### ISSUE THREAD

**Issue by duongvanba** [ts-stack/di#1]
I can not useFactory with async function, I you update it for me
I always use async factory in nestjs so i think it is better for us to bring this feature to this lib

**Comment by KostyaTretyak** [comment]
Can you provide a case where you need to use `useFactory` asynchronously?

**Comment by duongvanba** [comment]
Yes of course bro 
I'm using your lib in my extension's background script 
So it need to fetch all config from server before start running
Hope that you can update this for me

**Comment by duongvanba** [comment]
See this bro [https://docs.nestjs.com/fundamentals/async-providers]

**Comment by duongvanba** [comment]
I'm current using your lib in my project so I really hope that you can update this feature 
Thank you so much

**Comment by KostyaTretyak** [comment]
I also use this module for my node.js web framework, but I haven't had to get asynchronous configuration using `useFactory()`. In theory, this feature is easy to do without.

**Comment by duongvanba** [comment]
Yes bro
But when I use in browser I need call async config api right

**Comment by KostyaTretyak** [comment]
But you also can async get config and then call DI to get need instance.

**Comment by duongvanba** [comment]
Yeah you right
But if I have a lot services need to async construct and they depend
together
I will construct them separate then call DI right, I hope that DI can do it
for me
It's simple if we have small services number, it when number of services is
big it's too complex
You can you point me they way to implement async provider with your code, i
can pull it then do it myself
Thank you so much



Vào Th 5, 8 thg 10, 2020 vào lúc 23:25 Костя Третяк <
notifications@github.com> đã viết:

**Comment by KostyaTretyak** [comment]
First, you need to have a single injector for your entire application. You need to create this injector after you have received the configuration asynchronously.

For example, in your services you can get config this way:

```ts
import { Inject, Injectable } from '@ts-stack/di';

import { ConfigService } from './paht/to/config.service'; // this is a class with props you need.

@Injectable()
class SomeService1 {
  constructor(@Inject(ConfigService) private config: ConfigService) {}
}
```

And then, to get a single injector, you need to import all the services into one file:

```ts
import { ReflectiveInjector } from '@ts-stack/di';

import { functionToGetConfig } from './paht/to/function-to-get-config';
import { ConfigService } from './paht/to/config.service';
import { Service1 } from './paht/to/service1';
import { Service2 } from './paht/to/service2';

export async function getInjector() {
  return ReflectiveInjector.resolveAndCreate([
    { provide: ConfigService, useValue: await functionToGetConfig() },
    Service1,
    Service2,
    // Other services
  ]);
}
```

And then, use `getInjector()` in all places where you need to receive your services:

```ts
async function someFunctionOrMethod() {
  const injector = await getInjector();
  const service1 = injector.get(Service1);
}
```

**Comment by duongvanba** [comment]
Oh okay bro
Thank you so much

Vào Th 6, 9 thg 10, 2020 vào lúc 15:29 Костя Третяк <
notifications@github.com> đã viết:
